// This file is autogenerated by the hyperdispatch compiler
/* eslint-disable camelcase */

const { c, b4a, assert } = require('hyperdispatch/runtime')
const { version, getEncoding, setVersion } = require('./messages.js')

const defaultVersion = version

class Router {
  constructor () {
    this._handler0 = null
    this._handler1 = null
    this._handler2 = null
    this._handler3 = null
    this._handler4 = null
    this._handler5 = null
    this._handler6 = null

    this._missing = 7
  }

  add (name, handler) {
    switch (name) {
      case '@multiWriter/add-writer':
        this._handler0 = handler
        break
      case '@multiWriter/add-invite':
        this._handler1 = handler
        break
      case '@multiWriter/del-invite':
        this._handler2 = handler
        break
      case '@multiWriter/add-user':
        this._handler3 = handler
        break
      case '@multiWriter/del-user':
        this._handler4 = handler
        break
      case '@multiWriter/add-event':
        this._handler5 = handler
        break
      case '@multiWriter/del-event':
        this._handler6 = handler
        break
      default:
        throw new Error('Cannot register a handler for a nonexistent route: ' + name)
    }
    this._missing--
  }

  _checkAll () {
    assert(this._handler0 !== null, 'Missing handler for "@multiWriter/add-writer"')
    assert(this._handler1 !== null, 'Missing handler for "@multiWriter/add-invite"')
    assert(this._handler2 !== null, 'Missing handler for "@multiWriter/del-invite"')
    assert(this._handler3 !== null, 'Missing handler for "@multiWriter/add-user"')
    assert(this._handler4 !== null, 'Missing handler for "@multiWriter/del-user"')
    assert(this._handler5 !== null, 'Missing handler for "@multiWriter/add-event"')
    assert(this._handler6 !== null, 'Missing handler for "@multiWriter/del-event"')
  }

  async dispatch (message, context) {
    if (this._missing > 0) {
      this._checkAll()
    }

    setVersion(defaultVersion)

    const op = b4a.isBuffer(message) ? decode(message) : message

    switch (op.id) {
      case 0:
        return this._handler0(op.value, context)
      case 1:
        return this._handler1(op.value, context)
      case 2:
        return this._handler2(op.value, context)
      case 3:
        return this._handler3(op.value, context)
      case 4:
        return this._handler4(op.value, context)
      case 5:
        return this._handler5(op.value, context)
      case 6:
        return this._handler6(op.value, context)
      default:
        throw new Error('Handler not found for ID:' + op.id)
    }
  }
}

function encode (name, message, { version = defaultVersion } = {}) {
  const state = { buffer: null, start: 0, end: 0 }

  const route = getRouteByName(name)
  setVersion(version)

  c.uint.preencode(state, route.id)
  route.enc.preencode(state, message)

  state.buffer = b4a.allocUnsafe(state.end)
  c.uint.encode(state, route.id)
  route.enc.encode(state, message)

  return state.buffer
}

function decode (buffer, { version = defaultVersion } = {}) {
  const state = { buffer, start: 0, end: buffer.length }

  const id = c.uint.decode(state)
  const route = getRouteById(id)
  setVersion(version)

  const value = route.enc.decode(state)
  return { id, name: route.name, value }
}

const route0 = {
  name: '@multiWriter/add-writer',
  id: 0,
  enc: getEncoding('@multiWriter/writers')
}

const route1 = {
  name: '@multiWriter/add-invite',
  id: 1,
  enc: getEncoding('@multiWriter/invites')
}

const route2 = {
  name: '@multiWriter/del-invite',
  id: 2,
  enc: getEncoding('@multiWriter/invites')
}

const route3 = {
  name: '@multiWriter/add-user',
  id: 3,
  enc: getEncoding('@multiWriter/users')
}

const route4 = {
  name: '@multiWriter/del-user',
  id: 4,
  enc: getEncoding('@multiWriter/users')
}

const route5 = {
  name: '@multiWriter/add-event',
  id: 5,
  enc: getEncoding('@multiWriter/events')
}

const route6 = {
  name: '@multiWriter/del-event',
  id: 6,
  enc: getEncoding('@multiWriter/events')
}

function getRouteByName (name) {
  switch (name) {
    case '@multiWriter/add-writer':
      return route0
    case '@multiWriter/add-invite':
      return route1
    case '@multiWriter/del-invite':
      return route2
    case '@multiWriter/add-user':
      return route3
    case '@multiWriter/del-user':
      return route4
    case '@multiWriter/add-event':
      return route5
    case '@multiWriter/del-event':
      return route6
    default:
      throw new Error('Handler not found for name: ' + name)
  }
}

function getRouteById (id) {
  switch (id) {
    case 0:
      return route0
    case 1:
      return route1
    case 2:
      return route2
    case 3:
      return route3
    case 4:
      return route4
    case 5:
      return route5
    case 6:
      return route6
    default:
      throw new Error('Handler not found for ID: ' + id)
  }
}

module.exports = {
  version,
  encode,
  decode,
  Router
}
